#!/bin/sh

referenceHeader=`cat Header.txt`

totalFiles=0
incorrectFiles=0

for sourcePath in `find $1 -name *.cs`
do
	totalFiles=`expr $totalFiles + 1`
	testHeader=`head -16 $sourcePath`
	if [ "$testHeader" != "$referenceHeader" ]
	then
		incorrectFiles=`expr $incorrectFiles + 1`
		echo "Incorrect header: ${sourcePath#../}"
	fi
done

echo "Files checked:     $totalFiles"
echo "Incorrect headers: $incorrectFiles"

if [ $incorrectHeaders > 0 ]
then return 1
fi
