#!/bin/bash

PS1=HACK
source $HOME/.bashrc

cd $1/Wrappers/streamvis-wrappers-yarp
make
cp bin/libstreamvis-wrappers-yarp.so $2

cd $1/Wrappers/streamvis-wrappers-ros
make
cp bin/libstreamvis-wrappers-ros.so $2
