binaries: wrappers visualizer
	mkdir -p Binaries
	cp -r Wrappers/Binaries/* Binaries
	cp -r Visualizer/Binaries/* Binaries

wrappers:
	$(MAKE) -C Wrappers

visualizer:
	$(MAKE) -C Visualizer

.PHONY: wrappers visualizer
