/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Yarp
{
	public class BufferedPortImageRgb : Contactable
	{
		private HandleRef swigCPtr;

		internal BufferedPortImageRgb(IntPtr cPtr, bool cMemoryOwn)
			: base(yarpPINVOKE.BufferedPortImageRgbUpcast(cPtr), cMemoryOwn)
		{
			swigCPtr = new HandleRef(this, cPtr);
		}

		internal static HandleRef getCPtr(BufferedPortImageRgb obj)
		{
			return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
		}

		~BufferedPortImageRgb()
		{
			Dispose();
		}

		public override void Dispose()
		{
			lock (this)
			{
				if (swigCPtr.Handle != IntPtr.Zero && swigCMemOwn)
				{
					swigCMemOwn = false;
					yarpPINVOKE.delete_BufferedPortImageRgb(swigCPtr);
				}
				swigCPtr = new HandleRef(null, IntPtr.Zero);
				GC.SuppressFinalize(this);
				base.Dispose();
			}
		}

		public BufferedPortImageRgb()
			: this(yarpPINVOKE.new_BufferedPortImageRgb(), true)
		{
		}

		public override bool addOutput(string name)
		{
			bool ret = yarpPINVOKE.BufferedPortImageRgb_addOutput__SWIG_0(swigCPtr, name);
			return ret;
		}

		public override bool addOutput(string name, string carrier)
		{
			bool ret = yarpPINVOKE.BufferedPortImageRgb_addOutput__SWIG_1(swigCPtr, name, carrier);
			return ret;
		}

		public override bool addOutput(Contact contact)
		{
			bool ret = yarpPINVOKE.BufferedPortImageRgb_addOutput__SWIG_2(swigCPtr, Contact.getCPtr(contact));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
			return ret;
		}

		public override void close()
		{
			yarpPINVOKE.BufferedPortImageRgb_close(swigCPtr);
		}

		public override void interrupt()
		{
			yarpPINVOKE.BufferedPortImageRgb_interrupt(swigCPtr);
		}

		public int getPendingReads()
		{
			int ret = yarpPINVOKE.BufferedPortImageRgb_getPendingReads(swigCPtr);
			return ret;
		}

		public override Contact where()
		{
			Contact ret = new Contact(yarpPINVOKE.BufferedPortImageRgb_where(swigCPtr), true);
			return ret;
		}

		public override ConstString getName()
		{
			ConstString ret = new ConstString(yarpPINVOKE.BufferedPortImageRgb_getName(swigCPtr), true);
			return ret;
		}

		public ImageRgb prepare()
		{
			ImageRgb ret = new ImageRgb(yarpPINVOKE.BufferedPortImageRgb_prepare(swigCPtr), false);
			return ret;
		}

		public void write(bool forceStrict)
		{
			yarpPINVOKE.BufferedPortImageRgb_write__SWIG_0(swigCPtr, forceStrict);
		}

		public void write()
		{
			yarpPINVOKE.BufferedPortImageRgb_write__SWIG_1(swigCPtr);
		}

		public void writeStrict()
		{
			yarpPINVOKE.BufferedPortImageRgb_writeStrict(swigCPtr);
		}

		public void setStrict(bool strict)
		{
			yarpPINVOKE.BufferedPortImageRgb_setStrict__SWIG_0(swigCPtr, strict);
		}

		public void setStrict()
		{
			yarpPINVOKE.BufferedPortImageRgb_setStrict__SWIG_1(swigCPtr);
		}

		public ImageRgb read(bool shouldWait)
		{
			IntPtr cPtr = yarpPINVOKE.BufferedPortImageRgb_read__SWIG_0(swigCPtr, shouldWait);
			ImageRgb ret = (cPtr == IntPtr.Zero) ? null : new ImageRgb(cPtr, false);
			return ret;
		}

		public ImageRgb read()
		{
			IntPtr cPtr = yarpPINVOKE.BufferedPortImageRgb_read__SWIG_1(swigCPtr);
			ImageRgb ret = (cPtr == IntPtr.Zero) ? null : new ImageRgb(cPtr, false);
			return ret;
		}

		public ImageRgb lastRead()
		{
			IntPtr cPtr = yarpPINVOKE.BufferedPortImageRgb_lastRead(swigCPtr);
			ImageRgb ret = (cPtr == IntPtr.Zero) ? null : new ImageRgb(cPtr, false);
			return ret;
		}

		public bool isClosed()
		{
			bool ret = yarpPINVOKE.BufferedPortImageRgb_isClosed(swigCPtr);
			return ret;
		}

		public void setReplier(PortReader reader)
		{
			yarpPINVOKE.BufferedPortImageRgb_setReplier(swigCPtr, PortReader.getCPtr(reader));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public void onRead(ImageRgb datum)
		{
			yarpPINVOKE.BufferedPortImageRgb_onRead(swigCPtr, ImageRgb.getCPtr(datum));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public void useCallback(TypedReaderCallbackImageRgb callback)
		{
			yarpPINVOKE.BufferedPortImageRgb_useCallback__SWIG_0(swigCPtr, TypedReaderCallbackImageRgb.getCPtr(callback));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public void useCallback()
		{
			yarpPINVOKE.BufferedPortImageRgb_useCallback__SWIG_1(swigCPtr);
		}

		public void disableCallback()
		{
			yarpPINVOKE.BufferedPortImageRgb_disableCallback(swigCPtr);
		}

		public override bool setEnvelope(PortWriter envelope)
		{
			bool ret = yarpPINVOKE.BufferedPortImageRgb_setEnvelope(swigCPtr, PortWriter.getCPtr(envelope));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
			return ret;
		}

		public override bool getEnvelope(PortReader envelope)
		{
			bool ret = yarpPINVOKE.BufferedPortImageRgb_getEnvelope(swigCPtr, PortReader.getCPtr(envelope));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
			return ret;
		}

		public override int getInputCount()
		{
			int ret = yarpPINVOKE.BufferedPortImageRgb_getInputCount(swigCPtr);
			return ret;
		}

		public override int getOutputCount()
		{
			int ret = yarpPINVOKE.BufferedPortImageRgb_getOutputCount(swigCPtr);
			return ret;
		}

		public override void getReport(PortReport reporter)
		{
			yarpPINVOKE.BufferedPortImageRgb_getReport(swigCPtr, PortReport.getCPtr(reporter));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public override void setReporter(PortReport reporter)
		{
			yarpPINVOKE.BufferedPortImageRgb_setReporter(swigCPtr, PortReport.getCPtr(reporter));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public SWIGTYPE_p_void acquire()
		{
			IntPtr cPtr = yarpPINVOKE.BufferedPortImageRgb_acquire(swigCPtr);
			SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
			return ret;
		}

		public void release(SWIGTYPE_p_void handle)
		{
			yarpPINVOKE.BufferedPortImageRgb_release(swigCPtr, SWIGTYPE_p_void.getCPtr(handle));
		}

	}
}