/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Yarp
{
	public class BufferedPortBottle : Contactable
	{
		private HandleRef swigCPtr;

		internal BufferedPortBottle(IntPtr cPtr, bool cMemoryOwn)
			: base(yarpPINVOKE.BufferedPortBottleUpcast(cPtr), cMemoryOwn)
		{
			swigCPtr = new HandleRef(this, cPtr);
		}

		internal static HandleRef getCPtr(BufferedPortBottle obj)
		{
			return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
		}

		~BufferedPortBottle()
		{
			Dispose();
		}

		public override void Dispose()
		{
			lock (this)
			{
				if (swigCPtr.Handle != IntPtr.Zero && swigCMemOwn)
				{
					swigCMemOwn = false;
					yarpPINVOKE.delete_BufferedPortBottle(swigCPtr);
				}
				swigCPtr = new HandleRef(null, IntPtr.Zero);
				GC.SuppressFinalize(this);
				base.Dispose();
			}
		}

		public BufferedPortBottle()
			: this(yarpPINVOKE.new_BufferedPortBottle(), true)
		{
		}

		public override bool addOutput(string name)
		{
			bool ret = yarpPINVOKE.BufferedPortBottle_addOutput__SWIG_0(swigCPtr, name);
			return ret;
		}

		public override bool addOutput(string name, string carrier)
		{
			bool ret = yarpPINVOKE.BufferedPortBottle_addOutput__SWIG_1(swigCPtr, name, carrier);
			return ret;
		}

		public override bool addOutput(Contact contact)
		{
			bool ret = yarpPINVOKE.BufferedPortBottle_addOutput__SWIG_2(swigCPtr, Contact.getCPtr(contact));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
			return ret;
		}

		public override void close()
		{
			yarpPINVOKE.BufferedPortBottle_close(swigCPtr);
		}

		public override void interrupt()
		{
			yarpPINVOKE.BufferedPortBottle_interrupt(swigCPtr);
		}

		public new int getPendingReads()
		{
			int ret = yarpPINVOKE.BufferedPortBottle_getPendingReads(swigCPtr);
			return ret;
		}

		public override Contact where()
		{
			Contact ret = new Contact(yarpPINVOKE.BufferedPortBottle_where(swigCPtr), true);
			return ret;
		}

		public override ConstString getName()
		{
			ConstString ret = new ConstString(yarpPINVOKE.BufferedPortBottle_getName(swigCPtr), true);
			return ret;
		}

		public Bottle prepare()
		{
			Bottle ret = new Bottle(yarpPINVOKE.BufferedPortBottle_prepare(swigCPtr), false);
			return ret;
		}

		public new void write(bool forceStrict)
		{
			yarpPINVOKE.BufferedPortBottle_write__SWIG_0(swigCPtr, forceStrict);
		}

		public new void write()
		{
			yarpPINVOKE.BufferedPortBottle_write__SWIG_1(swigCPtr);
		}

		public void writeStrict()
		{
			yarpPINVOKE.BufferedPortBottle_writeStrict(swigCPtr);
		}

		public new void setStrict(bool strict)
		{
			yarpPINVOKE.BufferedPortBottle_setStrict__SWIG_0(swigCPtr, strict);
		}

		public new void setStrict()
		{
			yarpPINVOKE.BufferedPortBottle_setStrict__SWIG_1(swigCPtr);
		}

		public new Bottle read(bool shouldWait)
		{
			IntPtr cPtr = yarpPINVOKE.BufferedPortBottle_read__SWIG_0(swigCPtr, shouldWait);
			Bottle ret = (cPtr == IntPtr.Zero) ? null : new Bottle(cPtr, false);
			return ret;
		}

		public new Bottle read()
		{
			IntPtr cPtr = yarpPINVOKE.BufferedPortBottle_read__SWIG_1(swigCPtr);
			Bottle ret = (cPtr == IntPtr.Zero) ? null : new Bottle(cPtr, false);
			return ret;
		}

		public new Bottle lastRead()
		{
			IntPtr cPtr = yarpPINVOKE.BufferedPortBottle_lastRead(swigCPtr);
			Bottle ret = (cPtr == IntPtr.Zero) ? null : new Bottle(cPtr, false);
			return ret;
		}

		public new bool isClosed()
		{
			bool ret = yarpPINVOKE.BufferedPortBottle_isClosed(swigCPtr);
			return ret;
		}

		public new void setReplier(PortReader reader)
		{
			yarpPINVOKE.BufferedPortBottle_setReplier(swigCPtr, PortReader.getCPtr(reader));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public new void onRead(Bottle datum)
		{
			yarpPINVOKE.BufferedPortBottle_onRead(swigCPtr, Bottle.getCPtr(datum));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public new void useCallback(BottleCallback callback)
		{
			yarpPINVOKE.BufferedPortBottle_useCallback__SWIG_0(swigCPtr, BottleCallback.getCPtr(callback));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public new void useCallback()
		{
			yarpPINVOKE.BufferedPortBottle_useCallback__SWIG_1(swigCPtr);
		}

		public void disableCallback()
		{
			yarpPINVOKE.BufferedPortBottle_disableCallback(swigCPtr);
		}

		public override bool setEnvelope(PortWriter envelope)
		{
			bool ret = yarpPINVOKE.BufferedPortBottle_setEnvelope(swigCPtr, PortWriter.getCPtr(envelope));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
			return ret;
		}

		public override bool getEnvelope(PortReader envelope)
		{
			bool ret = yarpPINVOKE.BufferedPortBottle_getEnvelope(swigCPtr, PortReader.getCPtr(envelope));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
			return ret;
		}

		public override int getInputCount()
		{
			int ret = yarpPINVOKE.BufferedPortBottle_getInputCount(swigCPtr);
			return ret;
		}

		public override int getOutputCount()
		{
			int ret = yarpPINVOKE.BufferedPortBottle_getOutputCount(swigCPtr);
			return ret;
		}

		public override void getReport(PortReport reporter)
		{
			yarpPINVOKE.BufferedPortBottle_getReport(swigCPtr, PortReport.getCPtr(reporter));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public override void setReporter(PortReport reporter)
		{
			yarpPINVOKE.BufferedPortBottle_setReporter(swigCPtr, PortReport.getCPtr(reporter));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public SWIGTYPE_p_void acquire()
		{
			IntPtr cPtr = yarpPINVOKE.BufferedPortBottle_acquire(swigCPtr);
			SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
			return ret;
		}

		public void release(SWIGTYPE_p_void handle)
		{
			yarpPINVOKE.BufferedPortBottle_release(swigCPtr, SWIGTYPE_p_void.getCPtr(handle));
		}

	}
}