/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Yarp
{
	public class ITorqueControlRaw : IDisposable
	{
		private HandleRef swigCPtr;
		protected bool swigCMemOwn;

		internal ITorqueControlRaw(IntPtr cPtr, bool cMemoryOwn)
		{
			swigCMemOwn = cMemoryOwn;
			swigCPtr = new HandleRef(this, cPtr);
		}

		internal static HandleRef getCPtr(ITorqueControlRaw obj)
		{
			return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
		}

		~ITorqueControlRaw()
		{
			Dispose();
		}

		public virtual void Dispose()
		{
			lock (this)
			{
				if (swigCPtr.Handle != IntPtr.Zero && swigCMemOwn)
				{
					swigCMemOwn = false;
					yarpPINVOKE.delete_ITorqueControlRaw(swigCPtr);
				}
				swigCPtr = new HandleRef(null, IntPtr.Zero);
				GC.SuppressFinalize(this);
			}
		}

		public virtual bool getAxes(SWIGTYPE_p_int ax)
		{
			bool ret = yarpPINVOKE.ITorqueControlRaw_getAxes(swigCPtr, SWIGTYPE_p_int.getCPtr(ax));
			return ret;
		}

		public virtual bool setTorqueMode()
		{
			bool ret = yarpPINVOKE.ITorqueControlRaw_setTorqueMode(swigCPtr);
			return ret;
		}

		public virtual double getRefTorqueRaw(int j)
		{
			double ret = yarpPINVOKE.ITorqueControlRaw_getRefTorqueRaw(swigCPtr, j);
			return ret;
		}

		public virtual void getRefTorquesRaw(SWIGTYPE_p_double t)
		{
			yarpPINVOKE.ITorqueControlRaw_getRefTorquesRaw(swigCPtr, SWIGTYPE_p_double.getCPtr(t));
		}

		public virtual bool setTorquesRaw(SWIGTYPE_p_double t)
		{
			bool ret = yarpPINVOKE.ITorqueControlRaw_setTorquesRaw(swigCPtr, SWIGTYPE_p_double.getCPtr(t));
			return ret;
		}

		public virtual void setTorqueRaw(int j, double t)
		{
			yarpPINVOKE.ITorqueControlRaw_setTorqueRaw(swigCPtr, j, t);
		}

	}
}