/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Yarp
{
	public class PixelRgbInt : IDisposable
	{
		private HandleRef swigCPtr;
		protected bool swigCMemOwn;

		internal PixelRgbInt(IntPtr cPtr, bool cMemoryOwn)
		{
			swigCMemOwn = cMemoryOwn;
			swigCPtr = new HandleRef(this, cPtr);
		}

		internal static HandleRef getCPtr(PixelRgbInt obj)
		{
			return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
		}

		~PixelRgbInt()
		{
			Dispose();
		}

		public virtual void Dispose()
		{
			lock (this)
			{
				if (swigCPtr.Handle != IntPtr.Zero && swigCMemOwn)
				{
					swigCMemOwn = false;
					yarpPINVOKE.delete_PixelRgbInt(swigCPtr);
				}
				swigCPtr = new HandleRef(null, IntPtr.Zero);
				GC.SuppressFinalize(this);
			}
		}

		public SWIGTYPE_p_yarp__os__NetInt32 r
		{
			set
			{
				yarpPINVOKE.PixelRgbInt_r_set(swigCPtr, SWIGTYPE_p_yarp__os__NetInt32.getCPtr(value));
				if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
			}
			get
			{
				SWIGTYPE_p_yarp__os__NetInt32 ret = new SWIGTYPE_p_yarp__os__NetInt32(yarpPINVOKE.PixelRgbInt_r_get(swigCPtr), true);
				if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
				return ret;
			}
		}

		public SWIGTYPE_p_yarp__os__NetInt32 g
		{
			set
			{
				yarpPINVOKE.PixelRgbInt_g_set(swigCPtr, SWIGTYPE_p_yarp__os__NetInt32.getCPtr(value));
				if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
			}
			get
			{
				SWIGTYPE_p_yarp__os__NetInt32 ret = new SWIGTYPE_p_yarp__os__NetInt32(yarpPINVOKE.PixelRgbInt_g_get(swigCPtr), true);
				if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
				return ret;
			}
		}

		public SWIGTYPE_p_yarp__os__NetInt32 b
		{
			set
			{
				yarpPINVOKE.PixelRgbInt_b_set(swigCPtr, SWIGTYPE_p_yarp__os__NetInt32.getCPtr(value));
				if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
			}
			get
			{
				SWIGTYPE_p_yarp__os__NetInt32 ret = new SWIGTYPE_p_yarp__os__NetInt32(yarpPINVOKE.PixelRgbInt_b_get(swigCPtr), true);
				if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
				return ret;
			}
		}

		public PixelRgbInt()
			: this(yarpPINVOKE.new_PixelRgbInt__SWIG_0(), true)
		{
		}

		public PixelRgbInt(int n_r, int n_g, int n_b)
			: this(yarpPINVOKE.new_PixelRgbInt__SWIG_1(n_r, n_g, n_b), true)
		{
		}

	}
}