/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Yarp
{
	public class PortInfo : IDisposable
	{
		private HandleRef swigCPtr;
		protected bool swigCMemOwn;

		internal PortInfo(IntPtr cPtr, bool cMemoryOwn)
		{
			swigCMemOwn = cMemoryOwn;
			swigCPtr = new HandleRef(this, cPtr);
		}

		internal static HandleRef getCPtr(PortInfo obj)
		{
			return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
		}

		~PortInfo()
		{
			Dispose();
		}

		public virtual void Dispose()
		{
			lock (this)
			{
				if (swigCPtr.Handle != IntPtr.Zero && swigCMemOwn)
				{
					swigCMemOwn = false;
					yarpPINVOKE.delete_PortInfo(swigCPtr);
				}
				swigCPtr = new HandleRef(null, IntPtr.Zero);
				GC.SuppressFinalize(this);
			}
		}

		public PortInfo()
			: this(yarpPINVOKE.new_PortInfo(), true)
		{
		}

		public int tag
		{
			set
			{
				yarpPINVOKE.PortInfo_tag_set(swigCPtr, value);
			}
			get
			{
				int ret = yarpPINVOKE.PortInfo_tag_get(swigCPtr);
				return ret;
			}
		}

		public bool incoming
		{
			set
			{
				yarpPINVOKE.PortInfo_incoming_set(swigCPtr, value);
			}
			get
			{
				bool ret = yarpPINVOKE.PortInfo_incoming_get(swigCPtr);
				return ret;
			}
		}

		public bool created
		{
			set
			{
				yarpPINVOKE.PortInfo_created_set(swigCPtr, value);
			}
			get
			{
				bool ret = yarpPINVOKE.PortInfo_created_get(swigCPtr);
				return ret;
			}
		}

		public ConstString portName
		{
			set
			{
				yarpPINVOKE.PortInfo_portName_set(swigCPtr, ConstString.getCPtr(value));
			}
			get
			{
				IntPtr cPtr = yarpPINVOKE.PortInfo_portName_get(swigCPtr);
				ConstString ret = (cPtr == IntPtr.Zero) ? null : new ConstString(cPtr, false);
				return ret;
			}
		}

		public ConstString sourceName
		{
			set
			{
				yarpPINVOKE.PortInfo_sourceName_set(swigCPtr, ConstString.getCPtr(value));
			}
			get
			{
				IntPtr cPtr = yarpPINVOKE.PortInfo_sourceName_get(swigCPtr);
				ConstString ret = (cPtr == IntPtr.Zero) ? null : new ConstString(cPtr, false);
				return ret;
			}
		}

		public ConstString targetName
		{
			set
			{
				yarpPINVOKE.PortInfo_targetName_set(swigCPtr, ConstString.getCPtr(value));
			}
			get
			{
				IntPtr cPtr = yarpPINVOKE.PortInfo_targetName_get(swigCPtr);
				ConstString ret = (cPtr == IntPtr.Zero) ? null : new ConstString(cPtr, false);
				return ret;
			}
		}

		public ConstString carrierName
		{
			set
			{
				yarpPINVOKE.PortInfo_carrierName_set(swigCPtr, ConstString.getCPtr(value));
			}
			get
			{
				IntPtr cPtr = yarpPINVOKE.PortInfo_carrierName_get(swigCPtr);
				ConstString ret = (cPtr == IntPtr.Zero) ? null : new ConstString(cPtr, false);
				return ret;
			}
		}

		public ConstString message
		{
			set
			{
				yarpPINVOKE.PortInfo_message_set(swigCPtr, ConstString.getCPtr(value));
			}
			get
			{
				IntPtr cPtr = yarpPINVOKE.PortInfo_message_get(swigCPtr);
				ConstString ret = (cPtr == IntPtr.Zero) ? null : new ConstString(cPtr, false);
				return ret;
			}
		}

		public static readonly int PORTINFO_NULL = yarpPINVOKE.PortInfo_PORTINFO_NULL_get();
		public static readonly int PORTINFO_CONNECTION = yarpPINVOKE.PortInfo_PORTINFO_CONNECTION_get();
		public static readonly int PORTINFO_MISC = yarpPINVOKE.PortInfo_PORTINFO_MISC_get();

	}
}