/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Yarp
{
	public class TypedReaderCallbackBottle : IDisposable
	{
		private HandleRef swigCPtr;
		protected bool swigCMemOwn;

		internal TypedReaderCallbackBottle(IntPtr cPtr, bool cMemoryOwn)
		{
			swigCMemOwn = cMemoryOwn;
			swigCPtr = new HandleRef(this, cPtr);
		}

		internal static HandleRef getCPtr(TypedReaderCallbackBottle obj)
		{
			return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
		}

		~TypedReaderCallbackBottle()
		{
			Dispose();
		}

		public virtual void Dispose()
		{
			lock (this)
			{
				if (swigCPtr.Handle != IntPtr.Zero && swigCMemOwn)
				{
					swigCMemOwn = false;
					yarpPINVOKE.delete_TypedReaderCallbackBottle(swigCPtr);
				}
				swigCPtr = new HandleRef(null, IntPtr.Zero);
				GC.SuppressFinalize(this);
			}
		}

		public void onRead(Bottle datum)
		{
			yarpPINVOKE.TypedReaderCallbackBottle_onRead__SWIG_0(swigCPtr, Bottle.getCPtr(datum));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public void onRead(Bottle datum, TypedReaderBottle reader)
		{
			yarpPINVOKE.TypedReaderCallbackBottle_onRead__SWIG_1(swigCPtr, Bottle.getCPtr(datum), TypedReaderBottle.getCPtr(reader));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public TypedReaderCallbackBottle()
			: this(yarpPINVOKE.new_TypedReaderCallbackBottle(), true)
		{
		}

	}
}