/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.39
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

namespace Yarp
{
	public class TypedReaderProperty : IDisposable
	{
		private HandleRef swigCPtr;
		protected bool swigCMemOwn;

		internal TypedReaderProperty(IntPtr cPtr, bool cMemoryOwn)
		{
			swigCMemOwn = cMemoryOwn;
			swigCPtr = new HandleRef(this, cPtr);
		}

		internal static HandleRef getCPtr(TypedReaderProperty obj)
		{
			return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
		}

		~TypedReaderProperty()
		{
			Dispose();
		}

		public virtual void Dispose()
		{
			lock (this)
			{
				if (swigCPtr.Handle != IntPtr.Zero && swigCMemOwn)
				{
					swigCMemOwn = false;
					yarpPINVOKE.delete_TypedReaderProperty(swigCPtr);
				}
				swigCPtr = new HandleRef(null, IntPtr.Zero);
				GC.SuppressFinalize(this);
			}
		}

		public void setStrict(bool strict)
		{
			yarpPINVOKE.TypedReaderProperty_setStrict__SWIG_0(swigCPtr, strict);
		}

		public void setStrict()
		{
			yarpPINVOKE.TypedReaderProperty_setStrict__SWIG_1(swigCPtr);
		}

		public Property read(bool shouldWait)
		{
			IntPtr cPtr = yarpPINVOKE.TypedReaderProperty_read__SWIG_0(swigCPtr, shouldWait);
			Property ret = (cPtr == IntPtr.Zero) ? null : new Property(cPtr, false);
			return ret;
		}

		public Property read()
		{
			IntPtr cPtr = yarpPINVOKE.TypedReaderProperty_read__SWIG_1(swigCPtr);
			Property ret = (cPtr == IntPtr.Zero) ? null : new Property(cPtr, false);
			return ret;
		}

		public virtual void interrupt()
		{
			yarpPINVOKE.TypedReaderProperty_interrupt(swigCPtr);
		}

		public Property lastRead()
		{
			IntPtr cPtr = yarpPINVOKE.TypedReaderProperty_lastRead(swigCPtr);
			Property ret = (cPtr == IntPtr.Zero) ? null : new Property(cPtr, false);
			return ret;
		}

		public bool isClosed()
		{
			bool ret = yarpPINVOKE.TypedReaderProperty_isClosed(swigCPtr);
			return ret;
		}

		public void useCallback(TypedReaderCallbackProperty callback)
		{
			yarpPINVOKE.TypedReaderProperty_useCallback(swigCPtr, TypedReaderCallbackProperty.getCPtr(callback));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public virtual void disableCallback()
		{
			yarpPINVOKE.TypedReaderProperty_disableCallback(swigCPtr);
		}

		public int getPendingReads()
		{
			int ret = yarpPINVOKE.TypedReaderProperty_getPendingReads(swigCPtr);
			return ret;
		}

		public virtual ConstString getName()
		{
			ConstString ret = new ConstString(yarpPINVOKE.TypedReaderProperty_getName(swigCPtr), true);
			return ret;
		}

		public void setReplier(PortReader reader)
		{
			yarpPINVOKE.TypedReaderProperty_setReplier(swigCPtr, PortReader.getCPtr(reader));
			if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
		}

		public virtual SWIGTYPE_p_void acquire()
		{
			IntPtr cPtr = yarpPINVOKE.TypedReaderProperty_acquire(swigCPtr);
			SWIGTYPE_p_void ret = (cPtr == IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
			return ret;
		}

		public virtual void release(SWIGTYPE_p_void handle)
		{
			yarpPINVOKE.TypedReaderProperty_release(swigCPtr, SWIGTYPE_p_void.getCPtr(handle));
		}

	}
}